project_id = "tgrpblqazcpxylhiuzst"

[functions.admin-create-user]
verify_jwt = true

[functions.update-discord-status]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.mercadopago-create-preference]
verify_jwt = false
